### ISSUE TITLE
Missing ROM -- Apple II

### ISSUE THREAD

**Issue by weems** [OpenEmulatorProject/libemulation#15]
2015-01-07 01:52:38.947 OpenEmulator[39893:688335] Could not connect the action openDonate: to target of class DocumentController
libemulation: missing ROM
libemulation: could not init 'appleII.romD0'

**Comment by paulhagstrom** [comment]
The commit from Nov 20, 2013 removed the ROMs, pending decisions about how they should be distributed. They're still in the history, though, if you back up to just before that commit, you can copy them out and then put them back in your working tree (as untracked files).

**Comment by tobier** [comment]
Closing this as there is a workaround given by @paulhagstrom.

Need to figure out what to do with the roms...
