### ISSUE TITLE
"File couldn't be opened"

### ISSUE THREAD

**Issue by cbeust** [OpenEmulatorProject/libemulation#21]
Whenever I choose a template from the list (e.g "Apple ][ europlus", but it happens for all), I get:

![image](https://cloud.githubusercontent.com/assets/92322/12427770/8578a246-befa-11e5-9d6b-acf159867616.png)

What am I missing?

**Comment by cbeust** [comment]
Debugging into it, it seems to be caused by the fact the emulator cannot open "appleIIeuroplus.romD0".

I have roms, it's not quite clear to me where I should put them.

**Comment by jvernet** [comment]
Put them into the Resources folder inside a floder named roms.

**Comment by tobier** [comment]
Closing this as there is a workaround as suggested by @jvernet
